Venus - Copy/Models/Email.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Venus.Models
{
    public class Email
    {
        [Key]
        public string To { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
    }
}

Venus - Copy/Models/ErrorViewModel.cs
using System;

namespace Venus.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Venus - Copy/Models/RegistrationApproval.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Venus.Models
{
    public class RegistrationApproval
    {
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public string ZipCode { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string NPWP { get; set; }
        public string FieldOfBusiness { get; set; }
        public string PICName { get; set; }
        public string PICEmail { get; set; }
    }
}

Venus - Copy/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Venus.Models;

namespace Venus.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Venus - Copy/Controllers/RegistrationApprovalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Venus.Data;
using Venus.Models;

namespace Venus.Controllers
{
    public class RegistrationApprovalsController : Controller
    {
        private readonly VenusContext _context;

        public RegistrationApprovalsController(VenusContext context)
        {
            _context = context;
        }

        // GET: RegistrationApprovals
        public async Task<IActionResult> Index()
        {
            return View(await _context.RegistrationApproval.ToListAsync());
        }

        // GET: RegistrationApprovals/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var registrationApproval = await _context.RegistrationApproval
                .FirstOrDefaultAsync(m => m.Id == id);
            if (registrationApproval == null)
            {
                return NotFound();
            }

            return View(registrationApproval);
        }

        // GET: RegistrationApprovals/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: RegistrationApprovals/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CompanyName,Address,ZipCode,Telephone,Fax,NPWP,FieldOfBusiness,PICName,PICEmail")] RegistrationApproval registrationApproval)
        {
            if (ModelState.IsValid)
            {
                _context.Add(registrationApproval);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(registrationApproval);
        }

        // GET: RegistrationApprovals/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var registrationApproval = await _context.RegistrationApproval.FindAsync(id);
            if (registrationApproval == null)
            {
                return NotFound();
            }
            return View(registrationApproval);
        }

        // POST: RegistrationApprovals/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CompanyName,Address,ZipCode,Telephone,Fax,NPWP,FieldOfBusiness,PICName,PICEmail")] RegistrationApproval registrationApproval)
        {
            if (id != registrationApproval.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(registrationApproval);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RegistrationApprovalExists(registrationApproval.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(registrationApproval);
        }

        // GET: RegistrationApprovals/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var registrationApproval = await _context.RegistrationApproval
                .FirstOrDefaultAsync(m => m.Id == id);
            if (registrationApproval == null)
            {
                return NotFound();
            }

            return View(registrationApproval);
        }

        // POST: RegistrationApprovals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var registrationApproval = await _context.RegistrationApproval.FindAsync(id);
            _context.RegistrationApproval.Remove(registrationApproval);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RegistrationApprovalExists(int id)
        {
            return _context.RegistrationApproval.Any(e => e.Id == id);
        }
    }
}

Venus - Copy/Controllers/SendEmailController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Venus.Models;
using System.Net.Mail;

namespace Venus.Controllers
{
    public class SendEmailController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(Email em)
        {
            string to = em.To;
            string subject = em.Subject;
            string body = em.Body;
            MailMessage mm = new MailMessage();
            mm.To.Add(to);
            mm.Subject = subject;
            mm.Body = body;
            mm.From = new MailAddress("fseiei99@gmail.com");
            mm.IsBodyHtml = false;
            SmtpClient smtp = new SmtpClient("smtp.gmail.com");
            smtp.Port = 587;
            smtp.UseDefaultCredentials = false;
            smtp.EnableSsl = true;
            smtp.Credentials = new System.Net.NetworkCredential("fseiei99@gmail.com", "aaaaa");
            smtp.Send(mm);
            ViewBag.message = "The mail has been sent to " + em.To + " successfully.";

            return View();
        }
    }
}

Venus - Copy/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Starter Page</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Starter Page</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-6">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Card title</h5>

                            <p class="card-text">
                                Some quick example text to build on the card title and make up the bulk of the card's
                                content.
                            </p>

                            <a href="#" class="card-link">Card link</a>
                            <a href="#" class="card-link">Another link</a>
                        </div>
                    </div>

                    <div class="card card-primary card-outline">
                        <div class="card-body">
                            <h5 class="card-title">Card title</h5>

                            <p class="card-text">
                                Some quick example text to build on the card title and make up the bulk of the card's
                                content.
                            </p>
                            <a href="#" class="card-link">Card link</a>
                            <a href="#" class="card-link">Another link</a>
                        </div>
                    </div><!-- /.card -->
                </div>
                <!-- /.col-md-6 -->
                <div class="col-lg-6">
                    <div class="card">
                        <div class="card-header">
                            <h5 class="m-0">Featured</h5>
                        </div>
                        <div class="card-body">
                            <h6 class="card-title">Special title treatment</h6>

                            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                            <a href="#" class="btn btn-primary">Go somewhere</a>
                        </div>
                    </div>

                    <div class="card card-primary card-outline">
                        <div class="card-header">
                            <h5 class="m-0">Featured</h5>
                        </div>
                        <div class="card-body">
                            <h6 class="card-title">Special title treatment</h6>

                            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                            <a href="#" class="btn btn-primary">Go somewhere</a>
                        </div>
                    </div>
                </div>
                <!-- /.col-md-6 -->
                <!-- /.col-md-6 -->
                <div class="col-lg-6">
                    <div class="card">
                        <div class="card-header">
                            <h5 class="m-0">Featured</h5>
                        </div>
                        <div class="card-body">
                            <h6 class="card-title">Special title treatment</h6>

                            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                            <a href="#" class="btn btn-primary">Go somewhere</a>
                        </div>
                    </div>

                    <div class="card card-primary card-outline">
                        <div class="card-header">
                            <h5 class="m-0">Featured</h5>
                        </div>
                        <div class="card-body">
                            <h6 class="card-title">Special title treatment</h6>

                            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                            <a href="#" class="btn btn-primary">Go somewhere</a>
                        </div>
                    </div>
                </div>
                <!-- /.col-md-6 -->

            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

Venus - Copy/Views/RegistrationApprovals/Create.cshtml
@model Venus.Models.RegistrationApproval

@{
    ViewData["Title"] = "Create";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0"></h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Vendor Registration List</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">

            <!-- COLOR PALETTE -->
            <div class="card card-default color-palette-box">
                <div class="card-header">
                    <h3 class="card-title">
                        <i class="fas fa-tag"></i>
                        Vendor Registration List
                    </h3>
                </div>
                <div class="card-body">

                    <div class="row">
                        <div class="col-md-4">
                            <form asp-action="Create">
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                <div class="form-group">
                                    <label asp-for="CompanyName" class="control-label"></label>
                                    <input asp-for="CompanyName" class="form-control" />
                                    <span asp-validation-for="CompanyName" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Address" class="control-label"></label>
                                    <input asp-for="Address" class="form-control" />
                                    <span asp-validation-for="Address" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="ZipCode" class="control-label"></label>
                                    <input asp-for="ZipCode" class="form-control" />
                                    <span asp-validation-for="ZipCode" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Telephone" class="control-label"></label>
                                    <input asp-for="Telephone" class="form-control" />
                                    <span asp-validation-for="Telephone" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Fax" class="control-label"></label>
                                    <input asp-for="Fax" class="form-control" />
                                    <span asp-validation-for="Fax" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="NPWP" class="control-label"></label>
                                    <input asp-for="NPWP" class="form-control" />
                                    <span asp-validation-for="NPWP" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="FieldOfBusiness" class="control-label"></label>
                                    <input asp-for="FieldOfBusiness" class="form-control" />
                                    <span asp-validation-for="FieldOfBusiness" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="PICName" class="control-label"></label>
                                    <input asp-for="PICName" class="form-control" />
                                    <span asp-validation-for="PICName" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="PICEmail" class="control-label"></label>
                                    <input asp-for="PICEmail" class="form-control" />
                                    <span asp-validation-for="PICEmail" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <input type="submit" value="Create" class="btn btn-primary" />
                                </div>
                            </form>
                        </div>
                    </div>

                    <div>
                        <a asp-action="Index">Back to List</a>
                    </div>

                    @section Scripts {
                        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
                    }

                </div>
                <!-- /.card-body -->
            </div>

        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

Venus - Copy/Views/RegistrationApprovals/Delete.cshtml
@model Venus.Models.RegistrationApproval

@{
    ViewData["Title"] = "Delete";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0"></h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Vendor Registration List</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">

            <!-- COLOR PALETTE -->
            <div class="card card-default color-palette-box">
                <div class="card-header">
                    <h3 class="card-title">
                        <i class="fas fa-tag"></i>
                        Vendor Registration List
                    </h3>
                </div>
                <div class="card-body">

                    <h3>Are you sure you want to delete this?</h3>
                    <div>
                        <h4>RegistrationApproval</h4>
                        <hr />
                        <dl class="row">
                            <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.CompanyName)
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.CompanyName)
                            </dd>
                            <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.Address)
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.Address)
                            </dd>
                            <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.ZipCode)
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.ZipCode)
                            </dd>
                            <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.Telephone)
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.Telephone)
                            </dd>
                            <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.Fax)
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.Fax)
                            </dd>
                            <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.NPWP)
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.NPWP)
                            </dd>
                            <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.FieldOfBusiness)
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.FieldOfBusiness)
                            </dd>
                            <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.PICName)
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.PICName)
                            </dd>
                            <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.PICEmail)
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.PICEmail)
                            </dd>
                        </dl>

                        <form asp-action="Delete">
                            <input type="hidden" asp-for="Id" />
                            <input type="submit" value="Delete" class="btn btn-danger" /> |
                            <a asp-action="Index">Back to List</a>
                        </form>
                    </div>

                </div>
                <!-- /.card-body -->
            </div>

        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

Venus - Copy/Views/RegistrationApprovals/Details.cshtml
@model Venus.Models.RegistrationApproval

@{
    ViewData["Title"] = "Details";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0"></h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Vendor Registration List</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">

            <!-- COLOR PALETTE -->
            <div class="card card-default color-palette-box">
                <div class="card-header">
                    <h3 class="card-title">
                        <i class="fas fa-tag"></i>
                        Vendor Registration List
                    </h3>
                </div>
                <div class="card-body">
                    <dl class="row">
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.CompanyName)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.CompanyName)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Address)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Address)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.ZipCode)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.ZipCode)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Telephone)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Telephone)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Fax)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Fax)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.NPWP)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.NPWP)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.FieldOfBusiness)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.FieldOfBusiness)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.PICName)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.PICName)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.PICEmail)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.PICEmail)
                        </dd>
                    </dl>

                    <div>
                        <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
                        <a asp-action="Index">Back to List</a>
                    </div>
                </div>
                <!-- /.card-body -->
            </div>

        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

Venus - Copy/Views/Shared/_Sidebar.cshtml
  <!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a class="brand-link" asp-area="" asp-controller="Home" asp-action="Index">
        <center><img src="~/adminlte/dist/img/NewVenusSynInverted.png" style="width: 40%;"></center>
        @*<span class="brand-text font-weight-light">AdminLTE 3</span>*@
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <!-- <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                <div class="image">
                    <img src="~/adminlte/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
                </div>
                <div class="info">
                    <a href="#" class="d-block">Alexander Pierce</a>
                </div>
            </div>-->
        <!-- SidebarSearch Form -->
        <!--  <div class="form-inline">
        <div class="input-group" data-widget="sidebar-search">
            <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
            <div class="input-group-append">
                <button class="btn btn-sidebar">
                    <i class="fas fa-search fa-fw"></i>
                </button>
            </div>
        </div>
    </div> -->
        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
            with font-awesome or any other icon font library -->


                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="SendEmail" asp-action="Index">
                        <i class="nav-icon far fa-image"></i>
                        <p>
                            Payment Monitoring
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-columns"></i>
                        <p>
                            Repository
                        </p>
                    </a>
                </li>

                <li class="nav-header">Admin Console</li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="RegistrationApprovals" asp-action="Index">
                        <i class="nav-icon fas fa-ellipsis-h"></i>
                        <p> Registration List</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-file"></i>
                        <p>Additional Tools</p>
                    </a>
                </li>

            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
            <!-- /.sidebar -->
        </aside>